# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        # uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: 2.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #  run: deno fmt --check

      - name: Run linter
        run: deno lint src/ --rules-exclude=no-var, no-explicit-any DENO_FUTURE=1

      - name: Run tests
        run: deno test test/*.js
        
      - name: Run Inject Version
        run: deno run --allow-read --allow-write type/version.js

      - name: Commit and push version bump
        run: |
          git config --global user.email "handoko75@gmail.com"
          git config --global user.name "Handoko"
          # Force add even unchanged files by touching them
          find type/ -type f -exec touch {} \;
          git add type/
          git commit -m "chore: inject version [skip ci]" || echo "No changes to commit"
          git push